macro(configure_project)
    set(NAME ${PROJECT_NAME})
    print_config(${NAME})
endmacro()

macro(print_config NAME)
    message("")
    message("------------------------------------------------------------------------")
    message("-- Configuring ${NAME} ${PROJECT_VERSION}")
    message("------------------------------------------------------------------------")
    message("-- CMake              Cmake version and location   ${CMAKE_VERSION} (${CMAKE_COMMAND})")
    message("-- Compiler           C++ compiler version         ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}")
#    message("-- CMAKE_BUILD_TYPE   Build type                   ${CMAKE_BUILD_TYPE}")
    message("-- TARGET_PLATFORM    Target platform              ${CMAKE_SYSTEM_NAME}")
#    message("-- BUILD_STATIC       Build static                 ${BUILD_STATIC}")
#    message("-- USE_HSM_SDF        Build SDF HSM                ${USE_HSM_SDF}")
#    message("-- DEMO               Build demos                  ${DEMO}")
#    message("-- TOOL               Build tools                  ${TOOL}")
#    message("-- COVERAGE           Build code coverage          ${COVERAGE}")
#    message("-- TESTS              Build tests                  ${TESTS}")
#    message("-- ARCH_NATIVE        Enable native code           ${ARCH_NATIVE}")
#    message("-- DEBUG                                           ${DEBUG}")
#    message("-- PROF                                            ${PROF}")
    message("------------------------------------------------------------------------")
    message("")
endmacro()